services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_production
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d.production:/etc/nginx/conf.d:ro
      - ./backend:/var/www/backend:ro   # 👉 nécessaire pour index.php
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    container_name: backend_production
    environment:
      - APP_ENV=dev
      - APP_DEBUG=0
    expose:
      - "9000" # PHP-FPM port
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    container_name: frontend_production
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_BASE_URL:-https://portail.techem.fr/api}
    expose:
      - "3000" # SSR port
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
