--------------------------------------------------------
--  DDL for View WEB_CLIENT
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "LER_CP_DEV"."WEB_CLIENT" ("PKCLIENT", "ID", "NOM", "ADRESSE1", "ADRESSE2", "ADRESSE3", "CP", "VILLE", "ESPACECLIENT_SHOWIMMEUBLESARC", "ESPACECLIENT_SHOWFACTURES", "ESPACECLIENT_SHOWCHANTIERS", "ESPACECLIENT_SHOWBILLINGOCC", "CHGT_OCCUPANT_TYPE", "ESPACECLIENT_GESTION", "NOTEOCCUPANT", "ESPACECLIENT_DATEACTIVATIONCLI", "ESPACECLIENT_DATEACTIVATIONOCC", "ESPACECLIENT_UNIFICATIONLOGEMENT", "ESPACECLIENT_TICKETINTER", "CODEENT", "FKCLIENT") AS 
  SELECT 
PKCLIENT,ID,NOM,ADRESSE1,ADRESSE2,ADRESSE3,CP,VILLE,
ESPACECLIENT_SHOWIMMEUBLESARC,ESPACECLIENT_SHOWFACTURES,
ESPACECLIENT_SHOWCHANTIERS,ESPACECLIENT_SHOWBILLINGOCC,
CHGT_OCCUPANT_TYPE,ESPACECLIENT_GESTION,
NOTEOCCUPANT,ESPACECLIENT_DATEACTIVATIONCLI,
ESPACECLIENT_DATEACTIVATIONOCC, 
ESPACECLIENT_UNIFICATIONLOGEMENT, TICKETINTER as ESPACECLIENT_TICKETINTER,
CODEENT, FKCLIENT
FROM client
where 
client.actif = 'O'
;

--------------------------------------------------------
--  DDL for View WEB_SOUSTRAITANT
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "LER_CP_DEV"."WEB_SOUSTRAITANT" ("PKSOUSTRAITANT", "NOM", "DESCRIPTION", "TERRITOIRES", "PAYS", "ADRESSE", "CP", "VILLE", "PROTECTION", "ACTIF") AS 
  SELECT PKSOUSTRAITANT, NOM, DESCRIPTION, TERRITOIRES, PAYS, ADRESSE, CP, VILLE, PROTECTION, ACTIF FROM soustraitant WHERE ACTIF='O'
;